# Generated by Django 5.1.5 on 2025-01-17 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collections_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='collectornotes',
            options={'verbose_name_plural': 'collector notes'},
        ),
        migrations.AlterModelOptions(
            name='customertransactions',
            options={'verbose_name_plural': 'customer transactions'},
        ),
        migrations.AlterModelOptions(
            name='paymentplans',
            options={'verbose_name_plural': 'payment plans'},
        ),
    ]
